export { default as IndexPage } from './IndexPage';
export { default as LoginPage } from './LoginPage';
export { default as RegisterPage } from './RegisterPage';
export { default as AccountPage } from './AccountPage';
export { default as PlacesPage } from './PlacesPage';
export { default as ProfilePage } from './ProfilePage';
export { default as PlaceDetailPage } from './PlaceDetailPage';
export { default as BookingsPage } from './BookingsPage';
export { default as BookingPage } from './BookingPage';